version: 0.0
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing"
  pre_build: 
    commands:
      - echo Installing source NPM dependencies...
      - npm install -f
  build:
    commands:
      - echo Build started on `date`
      - cd ${PATH}
      - echo Compiling the Node.js code
      - npm run build:dev
  post_build:
    commands:
      - echo build Completed on `date`
